# Use the docker image as everything is run within docker containers
image: docker:latest

services:
  - docker:dind

variables:
  BACKEND_IMAGE_PATH: registry.gitlab.com/mjmcconnell.dev/react_playground/backend

stages:
  - test
  - build
  - deploy

# Run all tests via the Makefile
test-be:
  stage: test
  script:
    - docker build . -f Dockerfile.backend -t backend
    - docker run -i --volume $(pwd)/apps/backend:/usr/src backend make test

build-fe:
  stage: build
  script:
    # Build out the frontend source files using the docker file
    - docker build . -f Dockerfile.frontend -t frontend
    - docker run -i --volume $(pwd)/apps/frontend:/usr/src frontend make build
  only:
    - tags

push-backend:
  stage: deploy
  script:
    # Log into gitlab docker container registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Build the latest backend image using the current git tag
    - docker build -t $BACKEND_IMAGE_PATH:$CI_COMMIT_TAG . --file=Dockerfile.backend
    # Push the image up to the container registry
    - docker push $BACKEND_IMAGE_PATH:$CI_COMMIT_TAG
  only:
    - tags

push-frontend:
  stage: deploy
  image: python:latest
  script:
    # Install the AWS cli tool from python
    - pip install awscli
    # Push all the frontend build assets to the S3 bucket
    - aws s3 cp ./apps/frontend/dist/ s3://mjmcconnell-react-playground/ --recursive --include "*"
  only:
    - tags
