# Use the docker image as everything is run within docker containers
image: docker:latest

services:
  - docker:dind

variables:
  BACKEND_IMAGE_PATH: registry.gitlab.com/mjmcconnell.dev/react_playground/backend
  FRONTEND_IMAGE_PATH: registry.gitlab.com/mjmcconnell.dev/react_playground/frontend

stages:
  - test
  - deploy

# Run all tests via the Makefile
test:
  stage: test
  script:
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - pip install docker-compose
    - make test

deploy:
  stage: deploy
  script:
    # Log into gitlab docker container registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Build the latest images using the current git tag
    - docker build -t $BACKEND_IMAGE_PATH:$CI_COMMIT_TAG . --file=Dockerfile.backend
    - docker build -t $FRONTEND_IMAGE_PATH:$CI_COMMIT_TAG . --file=Dockerfile.frontend
    # Push the images up to the container registry
    - docker push BACKEND_IMAGE_PATH:$CI_COMMIT_TAG
    - docker push FRONTEND_IMAGE_PATH:$CI_COMMIT_TAG
  only:
    - tags
