# Use the docker image as everything is run within docker containers
image: docker:latest

services:
  - docker:dind

before_script:
  - curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - /usr/local/bin/docker-compose --version


# Build out the local docker files using the docker-compose tool and docker-compose.yaml file
build:
  stage: build
  script:
    - docker-compose build

# Run all tests via the Makefile
test:
  stage: test
  script:
    - make test

deploy:
  stage: deploy
  script:
    # Log into gitlab docker container registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Build the latest images using the current git tag
    - docker build --pull -t "$CI_REGISTRY:/backend:$CI_COMMIT_TAG"  . --file=Dockerfile.backend
    - docker build --pull -t "$CI_REGISTRY:/frontend:$CI_COMMIT_TAG"  . --file=Dockerfile.frontend
    # Push the images up to the container registry
    - docker push "$CI_REGISTRY:/backend:$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY:/frontend:$CI_COMMIT_TAG"
  only:
    - tags

