version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - frontend
      - backend
    volumes:
      - ./ops/ssl_certificates:/ssl_certificates:ro
      - ./ops/nginx/templates/default.conf:/etc/nginx/conf.d/default.conf

  frontend:
    build:
      context: ./
      dockerfile: /Dockerfile.frontend
    volumes:
      - ./apps/frontend:/usr/src
    working_dir: /usr/src
    command: make run

  backend:
    build:
      context: ./
      dockerfile: /Dockerfile.backend
    volumes:
      - ./apps/backend:/usr/src
    working_dir: /usr/src
    command: make run
