version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: /Dockerfile.frontend
    volumes:
      - ./apps/frontend:/usr/src
    ports:
      - 3000:3000
    working_dir: /usr/src
    command: make run

  backend:
    build:
      context: ./
      dockerfile: /Dockerfile.backend
    volumes:
      - ./apps/backend:/usr/src
    ports:
      - 8080:8080
    working_dir: /usr/src
    command: make run
